// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SanalGozluk.Data;

#nullable disable

namespace SanalGozluk.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251202203959_IlkKurulum")]
    partial class IlkKurulum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("SanalGozluk.Models.Gozluk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model3DUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResimUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YuzTipi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gozlukler");
                });
#pragma warning restore 612, 618
        }
    }
}
